[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 